### ISSUE TITLE
Operator name change ?

### ISSUE THREAD

**Issue by Tilapiatsu** [javl/blender-embroidery#1]
Hi ! Thanks @javl a lot for this amazing addon !

I'm not going to raise a real issue on your addon actually, I'm actually an addon developer. I'm currently working on an addon which enables import batching capability in blender, and I would really like to support your Embroidery addon completely.
My end goal would be to support most format possible to make importing as easy as possible in blender.
You can have a sneak peak of how it work here :

https://extensions.blender.org/add-ons/universal-multi-importer/

And I have a small issue related to the name of embroidery operator...
In short, my code is reading the import parameters from the `bl_idname` like this : 

`bpy.ops.import_scene.fbx.get_rna_type().properties`

but for a weird reason when I'm trying to read your parameters like this :

`bpy.ops.import.embroidery.get_rna_type().properties`

Blender doesn't seams to like it :(
![image](https://github.com/user-attachments/assets/f917bd78-f031-45dc-9128-fe8eabae2b5d)

So I've tried to rename the import operator by something else : 
`bl_idname = "import_scene.embroidery"`
or
`bl_idname = "wm.embroidery_import"`

and it works just fine.
( other importer look to use this naming convention )

I know it have nothing to do with your addon, but would you consider renaming the operator in order for me to support your addon?
It would be greatly apreciated :)

Thanks in advance.

Cheers

Tilapiatsu

**Comment by javl** [comment]
I've changed the name so it should work now.
I do want to request adding credit for the developers of the other addons you implement. Currently there doesn't seem to be any mention?

**Comment by Tilapiatsu** [comment]
Thanks @javl for being so reactive, and actually make the change!

The version using your addon is not published yet, and I will obviously mention your name and extention name/URL.
Just to be clear, my addon is just allowing other importer addon to be imported as a batch.
I'm currently planning to add two importers from the extension platform, including yours, and I've made sure any addon dependencies are easy to resolve for the user. 
![image](https://github.com/user-attachments/assets/3e4ed148-678c-404d-91a9-e10b3b35fc94)

It uses the extension platform install function `bpy.ops.extensions.package_install()`. So I'm not packaging or redistributing other addons, and the downloads counts of other addons will increase accordingly.

But most of the formats are build in to blender. 

How would you recommend me to properly credit other developers ? What about build in addon developers ?

**Comment by javl** [comment]
Ah great, thanks for clearing that up.
I'd say adding a link to the related repo in that list of installable addons might work well enough? And maybe add a small overview of available addons plus their sources to the Readme on Github?

**Comment by Tilapiatsu** [comment]
Yep sounds fair to me ! 
I think I might be ready for the release arround tomorrow evening. I'll keep you posted.
Thanks a lot for your guidance!
