### ISSUE TITLE
Blender freezes if 'import jump wires' is unticked with some design

### ISSUE THREAD

**Issue by Tilapiatsu** [javl/blender-embroidery#2]
Hello @javl,

I've been testing your addon quite a lot these days, and it look like skipping the import of jump wires leads to really long import time or maybe a fail of import, forcing me to force blender shutdown though the task manager.

This is happening only with some specific designs. I've tested many designs and formats l've found online, but I wasn't able to really identify what aspect of the design would be culprit.

here is two embroidery files : 
cat : which work both with or without importing jump wire
wolf : which work only with jump wire
[embroidery.zip](https://github.com/user-attachments/files/17788128/embroidery.zip)

And if you are curious, you can download other format of the same design on this website:
Cat :
https://forum.embroideres.com/files/file/3854-red-kitten-free-embroidery-design/
Wolf : 
https://forum.embroideres.com/files/file/170-wolf-free-embroidery-design/

I hope it will help you understand what's happening.

Thanks in advance

**Comment by javl** [comment]
Could you give the new version a change? v0.9.4. It's also in the Blender extension repo so you can install it directly from Blender's settings.

Found two large problems which should speed up the import dramatically. I think the shear slowness was the problem when loading the wolf file, making Blender hang.

**Comment by javl** [comment]
No response, and I think this was solved, so closing the issue.

**Comment by Tilapiatsu** [comment]
Sorry for letting without answer, I didn't saw your previous message. And yes I can confirm, its solves the issue and indeed speeds up the import quite a lot !
Thanks a lot of the push :)

**Comment by javl** [comment]
Great, thanks for letting me know :)
